"""add image_paths to medical_records

Revision ID: 25bfefcc645b
Revises: 5a50344fcd4e
Create Date: 2026-03-26 19:45:21.941857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bfefcc645b'
down_revision = '5a50344fcd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_paths', sa.String(length=1000), nullable=True, comment='病历关联的图片路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_column('image_paths')

    # ### end Alembic commands ###
